site_name: Neyrinck Audio
site_description: Our detailed Neyrinck Audio User Guide provides step-by-step instructions for setting up and using V-Control Pro with your DAW. Learn how to connect control surfaces like D-Command and FaderPort to Pro Tools, Cubase, Logic Pro X, and more. Discover advanced MIDI mapping techniques, troubleshooting tips, and optimize your audio production workflow. Perfect for sound engineers, music producers, and audio professionals seeking to enhance their studio experience with powerful control surface integration.

theme:
  name: mkdocs
  custom_dir: docs/overrides

nav:
  - Home: 'index.md'
  - V-Control Pro: './vcontrolpro/documentation/index.md'

markdown_extensions:
  - attr_list
  - meta