site_name: Neyrinck Audio
site_description: Our detailed Neyrinck Audio User Guide provides step-by-step instructions for setting up and using V-Control Pro with your DAW. Learn how to connect control surfaces like D-Command and FaderPort to Pro Tools, Cubase, Logic Pro X, and more. Discover advanced MIDI mapping techniques, troubleshooting tips, and optimize your audio production workflow. Perfect for sound engineers, music producers, and audio professionals seeking to enhance their studio experience with powerful control surface integration.

theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home: 'index.md'
  - V-Control Pro:
    - Welcome To V-Control Pro: './vcontrolpro/documentation/index.md'
    - Quick Start Guide: './vcontrolpro/documentation/Quick-Start-Guide.md'
    - Install And Run V-Control Pro : './vcontrolpro/documentation/Install-and-Run-V-Control-Pro.md'
    - V-Control Pro Licensing: './vcontrolpro/documentation/V-Control-Pro-Licensing.md'
    - Digidesign Control 24: './vcontrolpro/documentation/Digidesign-Control-24.md'
    - Avid/Digidesign C|24: './vcontrolpro/documentation/Avid-Digidesign-C24.md'
    - Digidesign Pro Control: './vcontrolpro/documentation/Digidesign-Pro-Control.md'


markdown_extensions:
  - attr_list
  - meta