site_name: Neyrinck User Guides
site_description: User Guides for Neyrinck Audio products.

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
nav:
  - Home: 'index.md'
  - V-Control Pro:
    - Welcome To V-Control Pro: './vcontrolpro/documentation/index.md'
    - System Requirements: './vcontrolpro/documentation/requirements.md'
    - Quick Start Guide: './vcontrolpro/documentation/quick-start-guide.md'
    - Install And Run V-Control Pro : './vcontrolpro/documentation/install-and-run-v-control-pro.md'
    - V-Control Pro Licensing: './vcontrolpro/documentation/v-control-pro-licensing.md'
    - Setting Up Control Surfaces:
      - Overview: './vcontrolpro/documentation/controllers-overview.md'
      - Setting Up Ethernet Controllers: './vcontrolpro/documentation/ethernet-controllers.md'
      - Setting Up Midi Controllers: './vcontrolpro/documentation/midi-controllers.md'
      - Setting Up Firewire Controllers: './vcontrolpro/documentation/firewire-controllers.md'
      - Avid D-Command: './vcontrolpro/documentation/d-command.md'
      - Digidesign Control 24: './vcontrolpro/documentation/control-24.md'
      - Avid/Digidesign C|24: './vcontrolpro/documentation/c24.md'
      - Digidesign Pro Control: './vcontrolpro/documentation/pro-control.md'
      - Digidesign Command 8: './vcontrolpro/documentation/command8.md'
      - Digidesign 003: './vcontrolpro/documentation/digidesign-003.md'
      - FaderPort V2 / iOStation 24c: './vcontrolpro/documentation/faderport-v2.md'
      - FaderPort 8 / 16: './vcontrolpro/documentation/faderport-8-16.md'
      - V-Console: './vcontrolpro/documentation/v-console.md'
      - V-Control Pro iPad App: './vcontrolpro/documentation/v-control-pro-ipad.md'
    - Setting Up DAWs / Media Apps:
      - Pro Tools: './vcontrolpro/documentation/pro-tools.md'
      - Logic Pro X: './vcontrolpro/documentation/logic-pro.md'
      - Cubase / Nuendo: './vcontrolpro/documentation/cubase-nuendo.md'
      - Mackie Control DAWs:
        - Getting Started: './vcontrolpro/documentation/mackie-control.md'
        - Ableton Live: './vcontrolpro/documentation/ableton-live.md'
        - Adobe Audition: './vcontrolpro/documentation/adobe-audition.md'
        - DaVinci Resolve: './vcontrolpro/documentation/davinci-resolve.md'
        - Digital Performer: './vcontrolpro/documentation/digital-performer.md'
        - FL Studio: './vcontrolpro/documentation/fl-studio.md'
        - FMOD Studio: './vcontrolpro/documentation/fmod-studio.md'
        - LUNA: './vcontrolpro/documentation/luna.md'
        - MIO Console: './vcontrolpro/documentation/mio-console.md'
        - MixBus: './vcontrolpro/documentation/mixbus.md'
        - Premiere Pro: './vcontrolpro/documentation/premiere-pro.md'
        - Reaper: './vcontrolpro/documentation/reaper.md'
        - Reason: './vcontrolpro/documentation/reason.md'
        - Sonar: './vcontrolpro/documentation/sonar.md'
        - Studio One: './vcontrolpro/documentation/studio-one.md'
        - Tracktion: './vcontrolpro/documentation/tracktion.md'
        - Wwise: './vcontrolpro/documentation/wwise.md'
    - Using MIDI Mode: './vcontrolpro/documentation/midi-mode.md'
    - Using V-Window: './vcontrolpro/documentation/v-window.md'
    - Feature Charts:
      - D-Command:
        - Pro Tools With D-Command: './vcontrolpro/documentation/feature-chart/dcommand-protools.md'
        - Logic Pro With D-Command: './vcontrolpro/documentation/feature-chart/dcommand-logic.md'
        - Studio One With D-Command: './vcontrolpro/documentation/feature-chart/dcommand-studio-one.md'
        - Cubase / Nuendo With D-Command: './vcontrolpro/documentation/feature-chart/dcommand-steinberg.md'
        - MixBus With D-Command: './vcontrolpro/documentation/feature-chart/dcommand-mixbus.md'
      - C|24:
        - Pro Tools With C|24: './vcontrolpro/documentation/feature-chart/c24-protools.md'
        - Logic Pro With C|24: './vcontrolpro/documentation/feature-chart/c24-logic.md'
        - Ableton Live With C|24: './vcontrolpro/documentation/feature-chart/c24-ableton-live.md'
        - MixBus With C|24: './vcontrolpro/documentation/feature-chart/c24-mixbus.md'
        - Studio One With C|24: './vcontrolpro/documentation/feature-chart/c24-studio-one.md'
        - Cubase / Nuendo With C|24: './vcontrolpro/documentation/feature-chart/c24-steinberg.md'
        - Digital Performer With C|24: './vcontrolpro/documentation/feature-chart/c24-performer.md'
        - LUNA With C|24: './vcontrolpro/documentation/feature-chart/c24-luna.md'
      - Control 24:
        - Ableton Live With Control 24: './vcontrolpro/documentation/feature-chart/control24-ableton-live.md'
        - Pro Tools With Control 24: './vcontrolpro/documentation/feature-chart/control24-pro-tools.md'
        - Logic Pro With Control 24: './vcontrolpro/documentation/feature-chart/control24-logic.md'
        - Ableton Live With Control 24: './vcontrolpro/documentation/feature-chart/control24-ableton-live.md'
        - MixBus With Control 24: './vcontrolpro/documentation/feature-chart/control24-mixbus.md'
        - Studio One With Control 24: './vcontrolpro/documentation/feature-chart/control24-studio-one.md'
        - Cubase / Nuendo With Control 24: './vcontrolpro/documentation/feature-chart/control24-steinberg.md'
        - Digital Performer With Control 24: './vcontrolpro/documentation/feature-chart/control24-performer.md'
        - LUNA With Control 24: './vcontrolpro/documentation/feature-chart/control24-luna.md'
      - Pro Control:
        - Pro Tools With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-pro-tools.md'
        - Logic Pro With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-logic.md'
        - Ableton Live With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-ableton-live.md'
        - MixBus With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-mixbus.md'
        - Studio One With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-studio-one.md'
        - Cubase / Nuendo With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-steinberg.md'
        - Digital Performer With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-performer.md'
        - LUNA With Pro Control: './vcontrolpro/documentation/feature-chart/procontrol-luna.md'
      - Command 8:
        - Pro Tools With Command 8: './vcontrolpro/documentation/feature-chart/command8-pro-tools.md'
        - Logic Pro With Command 8: './vcontrolpro/documentation/feature-chart/command8-logic.md'
        - Ableton Live With Command 8: './vcontrolpro/documentation/feature-chart/command8-ableton-live.md'
        - Studio One With Command 8: './vcontrolpro/documentation/feature-chart/command8-studio-one.md'
        - Cubase / Nuendo With Command 8: './vcontrolpro/documentation/feature-chart/command8-steinberg.md'
        - LUNA With Command 8: './vcontrolpro/documentation/feature-chart/command8-luna.md'
      - Digi 003:
        - Pro Tools With 003: './vcontrolpro/documentation/feature-chart/003-pro-tools.md'
        - Logic Pro With 003: './vcontrolpro/documentation/feature-chart/003-logic.md'
        - Ableton Live With 003: './vcontrolpro/documentation/feature-chart/003-ableton-live.md'
        - MixBus With 003: './vcontrolpro/documentation/feature-chart/003-mixbus.md'
        - Studio One With 003: './vcontrolpro/documentation/feature-chart/003-studio-one.md'
        - Cubase / Nuendo With 003: './vcontrolpro/documentation/feature-chart/003-steinberg.md'
        - LUNA With 003: './vcontrolpro/documentation/feature-chart/003-luna.md'
      - Others: './vcontrolpro/documentation/feature-charts.md'
    - Troubleshooting: './vcontrolpro/documentation/troubleshooting.md'
    - Additional Resources: './vcontrolpro/documentation/getting-help.md'
    - Release Notes: './vcontrolpro/documentation/release-notes.md'
  - Plug-Ins:
    - Spill:
      - Welcome To Spill: './spill/guide/index.md'
      - Quick Start Guide: './spill/guide/quick-start-guide.md'
      - Installation And Setup: './spill/guide/install-and-setup.md'
      - Activating the License: './spill/guide/licensing.md'
      - Using the spill/guide Plug-In: './spill/guide/usage.md'
  - iPad Apps:
    - V-Console:
      - Welcome To V-Console: './vconsole/guide/index.md'
    - V-Panner:
      - Welcome To V-Panner: './vpanner/guide/index.md'

markdown_extensions:
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
   